### ISSUE TITLE
compilation error with bitcode

### ISSUE THREAD

**Issue by liyukuang** [hilen/TSWeChat#12]
ld: 'TSWeChat-master/Pods/TSVoiceConverter/Sources/lib/libopencore-amrnb.a(wrapper.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I think I have already disabled bitcode, but the error still exists.

**Comment by hilen** [comment]
#8 

You should open build it with bitcode enable in TSVoiceConverter. Now I've been pushed a new commit to update the TSVoiceConverter's version to 0.1.2 . Have a try?
