### ISSUE TITLE
输入的表情超过一行时，输入框的高度未随之增加

### ISSUE THREAD

**Issue by hw20101101** [hilen/TSWeChat#13]
如图：
![qq20160902-0](https://cloud.githubusercontent.com/assets/9107226/18190282/16b52d14-70f4-11e6-9074-6bbb41357214.png)

**Comment by hilen** [comment]
好的，这个我会看看的，细节的处理有些还不是很到位

**Comment by hilen** [comment]
已修复，可以拽下最新的 master 分支查看
