### ISSUE TITLE
Emotion inputs don't have content offset 

### ISSUE THREAD

**Issue by wleofeng** [hilen/TSWeChat#15]
![simulator screen shot sep 3 2016 12 24 02 am](https://cloud.githubusercontent.com/assets/12073790/18222697/c35818ce-716c-11e6-86f0-17217bc13d5b.png)

I pull requested a solution for #13 , but after the cell expanded and user keeps going, the text content should have moved up while keeping the cell height fixed at the max height.

**Comment by hilen** [comment]
Thanks for your code 👍 , I've been merged
