### ISSUE TITLE
会迁移到swift 3.0吗？

### ISSUE THREAD

**Issue by vincentlong889** [hilen/TSWeChat#16]
会迁移到swift 3.0吗？

**Comment by hilen** [comment]
会的，等 Swift 3.0 发布后，我会统一修改一个版本，包括里面有些实现也会修改。现在没有进度就是因为太多变了 😂

**Comment by hilen** [comment]
嗯，正在更新。迁移需要一些时间 😂

**Comment by nnianhou-** [comment]
Swift3.0啥时候迁移完😂😂😂

**Comment by hilen** [comment]
最近略忙，久等哈

**Comment by bangq** [comment]
期待3

**Comment by sishenyihuba** [comment]
不知道hilen会不会做后续的Friends朋友圈功能

**Comment by hilen** [comment]
会做的，但是时间上并不确定。最近太忙了 😂

**Comment by hilen** [comment]
Swift 3.0 已经迁移完毕，各种可以 pod install 跑起来了，需要 CocoaPods 环境 1.1.1+  ，Xcode 8.1
