### ISSUE TITLE
为什么pod install会失败

### ISSUE THREAD

**Issue by codeloved** [hilen/TSWeChat#17]
- `TSVoiceConverter (= 0.1.2)` required by `Podfile`
  这个是什么错误,别的项目都没有问题

**Comment by hilen** [comment]
能再提供一些细节吗？

**Comment by codeloved** [comment]
好的,我把报的错误全部粘贴上,就是pod install的时候会飘红,试了几个电脑了都是这样的
[!] Unable to satisfy the following requirements:

- `TSVoiceConverter (= 0.1.2)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `TSVoiceConverter (= 0.1.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by hilen** [comment]
你的 CocoaPods 版本是 1.0+ 的吗？试试 0.39.0？ 
另外确保你的 `gem source -l` 源没有问题

**Comment by dingshunwei** [comment]
同样问题。还有yytext装半天装不上。

**Comment by hilen** [comment]
@dingshunwei 很可能跟你的 CocoaPods 有关系，这里有一篇文章可以看看：http://hilen.github.io/2016/10/24/ruby-cocoapods/   另外 TSWeChat  我暂时还没有支持 Swift 3.0

**Comment by hilen** [comment]
项目已经支持 Swift 3.0 了，另外需要 CocoaPods 1.1.1+ ，Xcode 8.1 ，可以 run 起来了
