### ISSUE TITLE
无法运行在 Xcode 8.1, swift3 环境

### ISSUE THREAD

**Issue by flyinghawker** [hilen/TSWeChat#19]
Hi Hilen,
        按照你所说，下载repo之后在项目下面运行 pod install，但是打开xcode的时候总是出现错误
<img width="1152" alt="screen shot 2016-11-29 at 12 07 02 pm" src="https://cloud.githubusercontent.com/assets/13193798/20722496/746442b0-b62c-11e6-98fa-88be925d160f.png">
        因为初学者，所以不是和你明白如何自行解决，貌似这个library是objective c，是不是需要在Xcode配置一些选项，谢谢啦。
Michael Chen

**Comment by hilen** [comment]
你的 CocoaPods 版本是？

**Comment by flyinghawker** [comment]
1.1.1

**Comment by hilen** [comment]
理论上环境是没有问题的。可以尝试下把 Pods , .xcworkspace 和 Podfile.lock 都删除然后再 pod install 试试。

**Comment by flyinghawker** [comment]
谢谢你的建议，可惜还是无法运行。在我运行 pod install的时候，有warning关于：
不知道有没有关联。
还是谢谢你的帮忙，我后面也会尝试自己研究一下。
​

**Comment by hilen** [comment]
另外可以检查下你的 `~/.cocoapods/repos/` 是否和官方同步。后续我会把 podfile 用到的 lib 指定下版本号。

**Comment by flyinghawker** [comment]
好的，多谢
