### ISSUE TITLE
希望把聊天部分独立成库，像chatto那样

### ISSUE THREAD

**Issue by zj2050** [hilen/TSWeChat#20]
希望把聊天部分独立成库，像chatto那样， 那样的话可用的地方就很多了，谢谢

**Comment by hilen** [comment]
聊天那部分之所以就没有选择独立成库是因为不具有抽象性。现在这样也可以让开发者自由的去适配自己的业务需求。  ：）

**Comment by zj2050** [comment]
起始独立的类似chatto那样的聊天部分还是很有需求的，但可能确实需要很好的抽象性， 和chatto相比，你的更丰富，如果可能可以将聊天部分单独抽象出来，如果准备做，我可以加入一起

**Comment by hilen** [comment]
嗯，感谢您的建议，以后如果此项目日后足够成熟的话，可以考虑做成像 chatto 那样的库。但目前暂时没有这个打算，最初这个项目的出发点还是在于分享实现方式等内容。
