### ISSUE TITLE
pod两次了失败

### ISSUE THREAD

**Issue by hhb19900618** [hilen/TSWeChat#22]
[!] Error installing YYText
[!] /usr/local/bin/git clone https://github.com/ibireme/YYText.git /var/folders/4z/dctdgmh94j73gysppdm9lf5h0000gp/T/d20170223-2742-8sv9po --template= --single-branch --depth 1 --branch 1.0.7

Cloning into '/var/folders/4z/dctdgmh94j73gysppdm9lf5h0000gp/T/d20170223-2742-8sv9po'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by hilen** [comment]
确定你的 CocoaPods 源是否可以下载，你可以使用通过 `gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/` 来使用 `https://gems.ruby-china.org/` 的源

**Comment by hhb19900618** [comment]
已经好了 O(∩_∩)O谢谢
