### ISSUE TITLE
真机iOS10进入聊天页面闪退

### ISSUE THREAD

**Issue by moxun33** [hilen/TSWeChat#25]
真机iOS10中，第一次进入聊天页面点击输入框会假死闪退；之后进入聊天界面就闪退了。

**Comment by hilen** [comment]
有没有堆栈信息？

**Comment by moxun33** [comment]
@hilen ![](https://ooo.0o0.ooo/2017/03/13/58c5fb155a326.png)

**Comment by hilen** [comment]
已修复，是因为 plist 里关于 `NSMicrophoneUsageDescription` 权限没有申请。可以查看最新的 master 分支
