### ISSUE TITLE
为何不更新了

### ISSUE THREAD

**Issue by HuangXiaoxing** [hilen/TSWeChat#31]
期待更多功能的开发

**Comment by hilen** [comment]
在等 Swift 5 和 Xcode 9 release，然后会陆续会开发一些功能

**Comment by ManiacMike** [comment]
@hilen 给大佬打call

**Comment by ManiacMike** [comment]
Xcode 9是和Swift 4一起release的吧，Swift 5这是什么发布？

**Comment by hilen** [comment]
错了，是 Swift4 。另外有依赖的库还没有更新

**Comment by ronanhardiman** [comment]
@hilen  Swift4 已更新 😊

**Comment by hilen** [comment]
已更新 Xcode 10.2.1，Swift 5
