### ISSUE TITLE
发送消息的状态MessageSendSuccessType应该如何使用呢？

### ISSUE THREAD

**Issue by YuanPan** [hilen/TSWeChat#32]
想在发送过程中有个loading，如果发送失败则有个红色的⚠️警告。应该是MessageSendSuccessType这个来控制的吧，求指点。

**Comment by hilen** [comment]
发送消息的时候 ChatModel 的 MessageSendSuccessType 初始化值是 sending，然后 cell 监听这个状态值，UI 层面去做一个 loading 即可
