### ISSUE TITLE
聊天界面刚进入时 cell上的文字是空的.滚动刷新后才有.

### ISSUE THREAD

**Issue by huFly** [hilen/TSWeChat#37]
是启用YYTEXT异步绘制的原因??

**Comment by hilen** [comment]
是的

**Comment by huFly** [comment]
----大哥.. 骗我呢...你明明设置了false.  找到原因了..ios11的tableView代理方法执行顺序变了, 先cellForRow,后 heightForRow. 导致setmodle时textLayout没有值, 文字的cell 是空的.

**Comment by huFly** [comment]
解决方式...将估算高度关闭. 希望有人能深度解析下ios 11的tableView变化...

**Comment by hilen** [comment]
iOS11 我还没有完全兼容。 podfile 里用到的库还没有更新~~所以...😂

**Comment by hilen** [comment]
已兼容
