### ISSUE TITLE
Performance anti-pattern in UI

### ISSUE THREAD

**Issue by saraseif** [hilen/TSWeChat#42]
Hello guys!

I found that in TSChatTimeCell and TSChatSystemCell, there are LabelViews with their background colors set to transparent (alpha between 0 and 1). I think it would be better not to use transparent or partially transparent views in repeating styles, like TableViewCells and inside for loops.

Due to my own experience and [this Apple document](https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/DrawingTips/DrawingTips.html), using transparency could be tricky, performance-wise.

Do you think it makes sense the code is refactored to improve performance?

**Comment by hilen** [comment]
Yeah, absolutely yes. I  didn't do anything about the performance of this project so far. So we can improve the performance off this project that you refer to. 

I will do it later.  XD
