### ISSUE TITLE
如何讓聊天氣泡中的文字變成可選擇像是UITextField那樣？

### ISSUE THREAD

**Issue by EllisShen** [hilen/TSWeChat#44]
我知道目前氣泡中的文字是用YYLabel元件，如果我想讓自泡中的文字變成可選擇(Selectable)，該如何做？

**Comment by hilen** [comment]
你可以尝试写正则匹配出来你想要的文字对它进行可选操作。
就好比里面解析电话号码一样。

**Comment by EllisShen** [comment]
@hilen  謝謝你的回覆

**Comment by hilen** [comment]
可以持有一个临时的 YYTextView，当触控到一个 YYTextView 的时候，设置这个临时的为当前的 YYTextView，这样是不是可以做到控制界面上就显示一个 UIMenu？

**Comment by EllisShen** [comment]
謝謝@hilen，這個主意挺好的，我來試試看
