### ISSUE TITLE
xcode10 跑不起来

### ISSUE THREAD

**Issue by eskyray** [hilen/TSWeChat#46]
使用xcode10打开项目，编译时报了35个错误，请问什么时候适配xcode10呢

**Comment by hilen** [comment]
目前还没有针对 Xcode 10 适配。后续适配完成会提交 commit 的

**Comment by ifrankyu** [comment]
关注，期待大佬更新

**Comment by zijiazhai** [comment]
关注，期待大佬更新

**Comment by dhhd917** [comment]
哈哈 同上期待大佬更新

**Comment by key3board** [comment]
感谢大佬期待更新 xcode10

**Comment by WS-Vincent** [comment]
大佬，请问有时间搞一下xcode10吗。。。我想看一下效果~

**Comment by hilen** [comment]
已更新 Xcode 10.2.1，Swift 5
