### ISSUE TITLE
umbrella header not found and could not build Objective-C module

### ISSUE THREAD

**Issue by JarrarOS** [hilen/TSWeChat#5]
编译完后会有这两个错误,百度查了很多资料,不知道怎么解决
umbrella header "ObjectMapper-umbrella.h" not found
 could not build Objective-C module 'ObjectMapper'

**Comment by hilen** [comment]
在目录执行 pod install 了吗？然后运行 TSWeChat.xcworkspace 试试

**Comment by JarrarOS** [comment]
执行了呢,也是不行啊.

/Users/cocoa/Documents/Xcode7_2/repository/TSWeChat-master/build/Pods.build/Debug-iphoneos/ObjectMapper.build/module.modulemap:2:19: error: umbrella header 'ObjectMapper-umbrella.h' not found
  umbrella header "ObjectMapper-umbrella.h"
                  ^
<unknown>:0: error: could not build Objective-C module 'ObjectMapper'

报错的里面说是编译 UIViewController + Extension.swift NSNotificationCenter + Block.swift TSModel.swift Devices+swift 这四个文件时有上面的错误

**Comment by hilen** [comment]
能提供更多的信息吗？ CocoaPods 的版本号是多少？Xcode 版本号？

**Comment by JarrarOS** [comment]
pod --version 0.39.0
Xcode Version 7.2 (7C68)

**Comment by hilen** [comment]
你能截个图看看吗？

**Comment by loev139** [comment]
是这样的。 开始是 一个桥接文件不存在，然后我给注释了。 之后，出现同样错误

**Comment by hilen** [comment]
确保 Xcode 版本是 7.3 ，另外 CocoaPods 是 0.39.0.
