### ISSUE TITLE
xcode10.2.1无法编译

### ISSUE THREAD

**Issue by fifastar** [hilen/TSWeChat#53]
最新clone的code，并使用xcode10.2.1编译后仍旧有15个错误（基本都为pod中的），看到有帖子说已经针对xcode和swift进行了升级，请问是哪里还需要配置么？谢谢

**Comment by hilen** [comment]
CocoaPods 版本是多少？ 另外，截图发下错误？

**Comment by fifastar** [comment]
CocoaPods 1.7.4, build error的截图如下，谢谢！
![屏幕快照 2019-07-18 下午4 25 52](https://user-images.githubusercontent.com/3735046/61441723-ce128280-a978-11e9-982b-f794cfcbb378.png)

**Comment by hilen** [comment]
已修复，我本机上可运行是由于 pods 文件夹缓存原因
目前已升级 podfile 内所有的 framework.
