### ISSUE TITLE
Xcode 10.3无法编译通过

### ISSUE THREAD

**Issue by yanjiahua** [hilen/TSWeChat#54]
macOS Mojave 10.14.6
Xcode 10.3

执行pod install后显示以下信息，这个步骤应该没有问题，版本看上去都是对的
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.8.2)
Using BSGridCollectionViewLayout (1.2.3)
Using BSImagePicker (2.10.0)
Using BSImageView (1.0.3)
Using Dollar (9.0.0)
Using INTULocationManager (4.3.2)
Using KeychainAccess (3.2.0)
Using Kingfisher (5.7.0)
Using ObjcExceptionBridging (1.0.1)
Using ObjectMapper (3.5.1)
Using Reveal-SDK (4)
Using RxBlocking (5.0.0)
Using RxCocoa (5.0.0)
Using RxRelay (5.0.0)
Using RxSwift (5.0.0)
Using SVProgressHUD (2.0.4)
Using SnapKit (5.0.0)
Using SwiftyJSON (4.3.0)
Using TSVoiceConverter (0.1.6)
Using TimedSilver (1.2.0)
Using UIColor_Hex_Swift (5.1.0)
Using XCGLogger (7.0.0)
Using XLActionController (5.0.0)
Using YYText (1.0.7)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 20 dependencies from the Podfile and 24 total pods installed.

打开TSWeChat.xcworkspace，编译RxSwift的时候会报一些错误，导致后面无法编译通过，相关报错信息如下：

/Users/yanjiahua/LearningIOS/TSWeChat/Pods/RxSwift/RxSwift/Observables/Delay.swift:114:58: Value of type 'RxTimeInterval' (aka 'DispatchTimeInterval') has no member 'reduceWithSpanBetween'

/Users/yanjiahua/LearningIOS/TSWeChat/Pods/RxSwift/RxSwift/Observables/Throttle.swift:74:53: Value of type 'RxTimeInterval' (aka 'DispatchTimeInterval') has no member 'reduceWithSpanBetween'

/Users/yanjiahua/LearningIOS/TSWeChat/Pods/RxSwift/RxSwift/Observables/Throttle.swift:80:16: Value of type 'RxTimeInterval' (aka 'DispatchTimeInterval') has no member 'isNow'

/Users/yanjiahua/LearningIOS/TSWeChat/Pods/RxSwift/RxSwift/Schedulers/VirtualTimeScheduler.swift:79:25: Value of type 'RxTime' (aka 'Date') has no member 'addingDispatchInterval'

在网上查了有人碰到类似问题，删除Xcode缓存文件重启后解决问题，这边试了几次，还是无法解决，不知是否是Xcode新版本的问题

**Comment by Demonsword27** [comment]
同问

**Comment by Demonsword27** [comment]
@yanjiahua  你好 一样的问题 不知道您目前是否有解决。

**Comment by F0F0FO** [comment]
@Wbqqqq @yanjiahua  

Podfile 文件中 
先将之前倒入的三方注释掉 执行pod install 移除所有三分 
再去掉注释 pod install 重新导入所有三方

mac os ：10.14.6 (18G87)
xcode   ：Version 10.3 (10G8)

编译成功可正常运行

**Comment by Demonsword27** [comment]
@AppleSpace  thanks  I solved it。

**Comment by yanjiahua** [comment]
@AppleSpace @Wbqqqq @hilen 

按 @AppleSpace 上面提到的方法测试，先屏蔽 def pods 和 end 中的所有模块，执行 pod install，然后取消屏蔽，再执行一次 pod install，打开TSWeChat.xcworkspace，可以编译成功，不会报错了，多谢大家！
