### ISSUE TITLE
Rxswift BSImagePicker都不能变异通过

### ISSUE THREAD

**Issue by zidonJ** [hilen/TSWeChat#55]
Xcode10.4

**Comment by hilen** [comment]
Xcode 10.4 是 beta 版？用 Xcode 10.3 试试呢？

**Comment by zidonJ** [comment]
> Xcode 10.4 是 beta 版？用 Xcode 10.3 试试呢？

podfile里的版本依赖都去掉了 就好了 依赖包的版本可能有互相依赖 导致了一些问题
