### ISSUE TITLE
ios9.3 code7.3 真机调试 编译不过,libopencore 非bitcode

### ISSUE THREAD

**Issue by ptphp** [hilen/TSWeChat#8]
> `Ld /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Products/Debug-iphoneos/TSVoiceConverter/TSVoiceConverter.framework/TSVoiceConverter normal arm64
    cd /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Products/Debug-iphoneos/TSVoiceConverter -L/Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Pods/TSVoiceConverter/Sources/lib -F/Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Products/Debug-iphoneos/TSVoiceConverter -filelist /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter.LinkFileList -install_name @rpath/TSVoiceConverter.framework/TSVoiceConverter -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -no_deduplicate -fembed-bitcode-marker -lopencore-amrnb -lopencore-amrwb -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter.swiftmodule -framework Foundation -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter_dependency_info.dat -o /Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Build/Products/Debug-iphoneos/TSVoiceConverter/TSVoiceConverter.framework/TSVoiceConverter

ld: '/Users/joseph/Desktop/data/projects/react-native-project/PtApp/ios/Pods/TSVoiceConverter/Sources/lib/libopencore-amrnb.a(wrapper.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by hilen** [comment]
找到 Xcode 工程左侧的 Pod 文件，找到 TSVoiceConverter 的 framework ，把 bitcode 打开

**Comment by ptphp** [comment]
能不能具体点?

**Comment by hilen** [comment]
![image](https://cloud.githubusercontent.com/assets/2245840/15137650/b8398e6e-16bd-11e6-9f6e-5dacbbfd07f1.png)

**Comment by ptphp** [comment]
谢谢
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


网上搜了下,用这个代码好像也可以放到Podfile里,

**Comment by hilen** [comment]
好的，后续我把 TSVoiceConverter 的也改下。多谢提议 👍

**Comment by fyt10060** [comment]
/Users/fyt/Desktop/HostApp/HostApp/Pods/TSVoiceConverter/Sources/lib/libopencore-amrnb.a(wrapper.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64  打开了bitcode依然提示这个，好像这意思是这个库里用的libopencore-amrnb.a是不支持bitcode 的

**Comment by hilen** [comment]
你打开的是哪个的 bitcode?

**Comment by fyt10060** [comment]
TSVoiceConverter...不至于那么傻还去打开别的framework的。。。我从美恰的SDK里面找到了编译了bitcode的这libopencore-amr两个文件，替换了pod的文档里的旧的两个就可以用了。。我本来想传上来无奈github传文件实在是慢，翻着墙也传不上文件来。。。

**Comment by hilen** [comment]
好吧，pod 版本对不对啊？ 0.39.0 - -

**Comment by fyt10060** [comment]
我不是，用的1.0.0

**Comment by hilen** [comment]
请用 0.39.0 ，英文版的 readme 我忘记更新了

**Comment by yuansf** [comment]
我也遇到了这个问题，模拟器可以运行，真机不行

**Comment by hilen** [comment]
具体细节呢？

**Comment by yuansf** [comment]
真机运行报错
`Ld /Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Products/Debug-iphoneos/TSVoiceConverter.framework/TSVoiceConverter normal arm64
    cd /Users/alivincent/Documents/TSWeChat/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Products/Debug-iphoneos -L/Users/alivincent/Documents/TSWeChat/Pods/TSVoiceConverter/Sources/lib -F/Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Products/Debug-iphoneos -filelist /Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter.LinkFileList -install_name @rpath/TSVoiceConverter.framework/TSVoiceConverter -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -no_deduplicate -fembed-bitcode-marker -lopencore-amrnb -lopencore-amrwb -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter.swiftmodule -framework Foundation -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Intermediates/Pods.build/Debug-iphoneos/TSVoiceConverter.build/Objects-normal/arm64/TSVoiceConverter_dependency_info.dat -o /Users/alivincent/Library/Developer/Xcode/DerivedData/TSWeChat-gbojkcxfjypbokamjwptzifwthjv/Build/Products/Debug-iphoneos/TSVoiceConverter.framework/TSVoiceConverter

ld: '/Users/alivincent/Documents/TSWeChat/Pods/TSVoiceConverter/Sources/lib/libopencore-amrnb.a(wrapper.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by hilen** [comment]
上面有答案，TSVoiceConverter 的 bitcode 打开

**Comment by yuansf** [comment]
打开了的，依然一样的错误

**Comment by yuansf** [comment]
ok了，TSVoiceConverter关闭就行
